check the DB2 instance path and if db2updvX exists, added cmdline options

diff --git a/db2dbs b/db2dbs
--- a/db2dbs
+++ b/db2dbs
@@ -4,22 +4,43 @@
 #
 # by Helmut K. C. Tessarek
 # name: db2dbs
-# parameter[s]: [script name]
+# parameter[s]: [-f <scriptname>] [-b <baseInstallpathOfDB2>] [-h]
 
 #
 #  global variables
 #
 
+DFTPATH="/opt/IBM/db2/V8.1 /usr/opt/db2_08_01 /opt/ibm/db2/V9.1 /opt/IBM/db2/V9.1"
 PROGNAME=$(/bin/basename $0)
 SU=/bin/su
 
-if [ "`uname`" = "Linux" ]
+#
+# parse command line into arguments
+#
+
+set -- `getopt b:f:h $*`
+# check result of parsing
+if [ $? != 0 ]
 then
-        _DB2_INST_DIR=/opt/ibm/db2/V9.1
-else
-        _DB2_INST_DIR=/opt/IBM/db2/V9.1
+        exit 1
 fi
-_DB2_INSTLIST=$_DB2_INST_DIR/instance/db2ilist
+while [ $1 != -- ]
+do
+        case $1 in
+        -b)     # set up the -b flag
+                BFLG=1
+                BARG=$2
+                shift;;
+        -f)     # set up the -f flag
+                FFLG=1
+                FARG=$2
+                shift;;
+        -h)     # set up the -h flag
+                HFLG=1;;
+        esac
+        shift   # next flag
+done
+shift   # skip --
 
 #
 #  functions
@@ -31,9 +52,40 @@ function ERR
   exit 1
 }
 
+function HELP
+{
+  echo "Usage: $PROGNAME [-f <scriptname>] [-b <baseInstallpathOfDB2>] [-h]"
+  exit 1
+}
+
+if [ "$HFLG" = "1" ]
+then
+  HELP
+fi
+
 #
 #  main
 #
+
+for p in $DFTPATH
+do
+  if [ -d $p ]
+  then
+    _DB2_INST_DIR=$p
+  fi
+done
+
+if [ ! -z "$BARG" ]
+then
+  _DB2_INST_DIR=$BARG
+fi
+
+if [ -z "$_DB2_INST_DIR" ]
+then
+  ERR "install directory not found. specify it with -b option"
+fi
+
+_DB2_INSTLIST=$_DB2_INST_DIR/instance/db2ilist
 
 if [ "`id -u`" != "0" ]; then
   ERR "you must be root to run this program"
@@ -63,8 +115,8 @@ do
      if [ "$LOCAL" == "Indirect" ]; then
        echo Database $ACT_DB
 
-       if [ ! -z "$1" ]; then
-          sed "s/DBNAME/$ACT_DB/g" $1 >/tmp/$ACT_DB
+       if [ ! -z "$FARG" ]; then
+          sed "s/DBNAME/$ACT_DB/g" $FARG >/tmp/$ACT_DB
           
           $SU - $ACT_INST -c "db2 -tvf /tmp/$ACT_DB"
           
diff --git a/db2updt b/db2updt
--- a/db2updt
+++ b/db2updt
@@ -4,25 +4,39 @@
 #
 # by Helmut K. C. Tessarek
 # name: db2updt
-# parameter[s]: none
+# parameter[s]: [-b <baseInstallpathOfDB2>] [-h]
 
 #
 #  global variables
 #
 
+DFTPATH="/opt/IBM/db2/V8.1 /usr/opt/db2_08_01 /opt/ibm/db2/V9.1 /opt/IBM/db2/V9.1"
 PROGNAME=$(/bin/basename $0)
 SU=/bin/su
 
-if [ "`uname`" = "Linux" ]
+#
+# parse command line into arguments
+#
+
+set -- `getopt b:h $*`
+# check result of parsing
+if [ $? != 0 ]
 then
-        _DB2_INST_DIR=/opt/ibm/db2/V9.1
-else
-        _DB2_INST_DIR=/opt/IBM/db2/V9.1
+        exit 1
 fi
-_DB2_INSTLIST=$_DB2_INST_DIR/instance/db2ilist
-_DB2_DASLIST=$_DB2_INST_DIR/instance/daslist
-_DB2_IUPDT=$_DB2_INST_DIR/instance/db2iupdt
-_DB2_DASUPDT=$_DB2_INST_DIR/instance/dasupdt
+while [ $1 != -- ]
+do
+        case $1 in
+        -b)     # set up the -b flag
+                BFLG=1
+                BARG=$2
+                shift;;
+        -h)     # set up the -h flag
+                HFLG=1;;
+        esac
+        shift   # next flag
+done
+shift   # skip --
 
 #
 #  functions
@@ -34,9 +48,51 @@ function ERR
   exit 1
 }
 
+function HELP
+{
+  echo "Usage: $PROGNAME [-b <baseInstallpathOfDB2>] [-h]"
+  exit 1
+}
+
+if [ "$HFLG" = "1" ]
+then
+  HELP
+fi
+
 #
 #  main
 #
+
+for p in $DFTPATH
+do
+  if [ -d $p ]
+  then
+    _DB2_INST_DIR=$p
+  fi
+done
+
+if [ ! -z "$BARG" ]
+then
+  _DB2_INST_DIR=$BARG
+fi
+
+if [ -z "$_DB2_INST_DIR" ]
+then
+  ERR "install directory not found. specify it with -b option"
+fi
+
+_DB2_INSTLIST=$_DB2_INST_DIR/instance/db2ilist
+_DB2_DASLIST=$_DB2_INST_DIR/instance/daslist
+_DB2_IUPDT=$_DB2_INST_DIR/instance/db2iupdt
+_DB2_DASUPDT=$_DB2_INST_DIR/instance/dasupdt
+
+for i in 8 9 10 11
+do
+  if [ -x $_DB2_INST_DIR/bin/db2updv$i ]
+  then
+    _DB2_UPD=db2updv$i
+  fi
+done
 
 if [ "`id -u`" != "0" ]; then
   ERR "you must be root to run this program"
@@ -57,7 +113,6 @@ fi
 if [ ! -x $_DB2_DASUPDT ]; then
   ERR "File $_DB2_DASUPDT not found (db2 may not be installed)"
 fi
-
 
 for ACT_INST in $($_DB2_INSTLIST 2>/dev/null)
 do
@@ -91,6 +146,11 @@ do
                            db2 BIND ~/sqllib/bnd/@db2cli.lst GRANT PUBLIC BLOCKING ALL;\
                            db2 BIND ~/sqllib/bnd/db2schema.bnd BLOCKING ALL GRANT PUBLIC sqlerror continue;\
                            db2 CONNECT RESET"
+       
+       if [ ! -z "$_DB2_UPD" ]
+       then
+         $SU - $ACT_INST -c "$_DB2_UPD -d $ACT_DB"
+       fi
      fi
   done
 done
